/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedor;

import AccesoDatos.FachadaBD;
import modelo.Empleado;

/**
 *
 * @author Fernando
 */
public class PanelProveedores extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    FachadaBD fachada;
    Empleado permisosEmpleado;
    public PanelProveedores(FachadaBD f,Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bRegistrarP = new javax.swing.JButton();
        bConsultarP = new javax.swing.JButton();
        bListarProveedores = new javax.swing.JButton();
        panelCentralProveedores = new javax.swing.JPanel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Proveedores"));

        bRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrarPro.png"))); // NOI18N
        bRegistrarP.setText("Nuevo");
        bRegistrarP.setToolTipText("Registrar Proveedor");
        bRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarPActionPerformed(evt);
            }
        });

        bConsultarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarPro.png"))); // NOI18N
        bConsultarP.setText("Consultar");
        bConsultarP.setToolTipText("Consultar Proveedor");
        bConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarPActionPerformed(evt);
            }
        });

        bListarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar Proveedor.png"))); // NOI18N
        bListarProveedores.setText("Lista");
        bListarProveedores.setToolTipText("Listar Proveedores");
        bListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRegistrarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bConsultarP, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(bListarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bListarProveedores)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCentralProveedoresLayout = new javax.swing.GroupLayout(panelCentralProveedores);
        panelCentralProveedores.setLayout(panelCentralProveedoresLayout);
        panelCentralProveedoresLayout.setHorizontalGroup(
            panelCentralProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        panelCentralProveedoresLayout.setVerticalGroup(
            panelCentralProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentralProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentralProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("Gestionar Proveedor");

        getAccessibleContext().setAccessibleName("Menú Clientes");
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarPActionPerformed
        // TODO add your handling code here:
        panelCentralProveedores.removeAll();
        PanelRegistroProveedor obj=new PanelRegistroProveedor(fachada,permisosEmpleado);
        panelCentralProveedores.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);

    }//GEN-LAST:event_bRegistrarPActionPerformed

    private void bConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarPActionPerformed
        // TODO add your handling code here:
        panelCentralProveedores.removeAll();
        PanelConsultarProveedor obj=new PanelConsultarProveedor(fachada,permisosEmpleado);
        panelCentralProveedores.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bConsultarPActionPerformed

    private void bListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarProveedoresActionPerformed
        // TODO add your handling code here:
        panelCentralProveedores.removeAll();
        PanelListadoProveedores obj=new PanelListadoProveedores(fachada,permisosEmpleado);
        panelCentralProveedores.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bListarProveedoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultarP;
    private javax.swing.JButton bListarProveedores;
    private javax.swing.JButton bRegistrarP;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCentralProveedores;
    // End of variables declaration//GEN-END:variables
}
