/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedor;

import AccesoDatos.FachadaBD;
import controlador.controladorProveedor;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.Proveedor;
import vista.Compras.PanelComprasXProveedor;
import vista.Compras.PanelRegistroCompra;
import vista.Compras.PanelRegistroComprasAntiguas;
import vista.Producto.PanelRegistroProducto;

/**
 *
 * @author usuario
 */
public class PanelListadoProveedores extends javax.swing.JPanel {

    /**
     * Creates new form panelListadoProductos
     */
    controladorProveedor controlador;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    JFrame frame;
    PanelRegistroCompra panelRegistroCompra;
    PanelRegistroComprasAntiguas panelComprasAntiguas;
    PanelComprasXProveedor panelComprasXProveedor;
    PanelRegistroProducto panelRegistroProducto;
    int opcion;

    public PanelListadoProveedores(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlador = new controladorProveedor(fachada);
        initComponents();
        Object[][] datos = controlador.listarProductos();
        Object[] nCol = {"Id Proveedor", "Nombre", "Direccion", "Telefono", "Saldo"};
        tablaProductos.setModel(new DefaultTableModel(datos, nCol));
        botonSeleccionar.setVisible(false);
    }
    /*Opcion:
     * 1. panelRegistroCompra
     * 2. panelRegistroComprasAntiguas
     * 3. panelComprasXProveedor
     * 4. panelRegistroProducto
     */
    public PanelListadoProveedores(FachadaBD f, Empleado pE, int op) {
        permisosEmpleado = pE;
        fachada = f;
        controlador = new controladorProveedor(fachada);
        opcion = op;
        initComponents();
        Object[][] datos = controlador.listarProductos();
        Object[] nCol = {"Id Proveedor", "Nombre", "Direccion", "Telefono", "Saldo"};
        tablaProductos.setModel(new DefaultTableModel(datos, nCol));
        botonSeleccionar.setEnabled(true);
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    public void setPanelRegistroCompra(PanelRegistroCompra panelRegistroCompra) {
        this.panelRegistroCompra = panelRegistroCompra;
    }

    public void setPanelComprasAntiguas(PanelRegistroComprasAntiguas panelComprasAntiguas) {
        this.panelComprasAntiguas = panelComprasAntiguas;
    }

    public void setPanelComprasXProveedor(PanelComprasXProveedor panelComprasXProveedor) {
        this.panelComprasXProveedor = panelComprasXProveedor;
    }
    
    public void setPanelRegistroProducto(PanelRegistroProducto panelRegistroProducto){
        this.panelRegistroProducto = panelRegistroProducto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonSeleccionar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Proveedores"));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProveedor", "Nombre", "Direccion", "Telefono", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSeleccionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionar)
                    .addComponent(botonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if(fila!=-1){
            Proveedor p = new Proveedor();
            p.setidProveedor(tablaProductos.getValueAt(fila,0)+"");
            p.setnombreProveedor(tablaProductos.getValueAt(fila,1)+"");
            
            switch(opcion){
                case 1:
                    panelRegistroCompra.setProveedor(p);
                    break;
                case 2:
                    panelComprasAntiguas.setProveedor(p);
                    break;
                case 3:
                    panelComprasXProveedor.setProveedor(p);
                    break;
                case 4:
                    panelRegistroProducto.setProveedor(p);
                    break;
            }
            frame.dispose();
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        PanelRegistroProveedor proveedorNuevo = new PanelRegistroProveedor(fachada, permisosEmpleado);
        JFrame registro = new JFrame();
        registro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        registro.add(proveedorNuevo);
        registro.setSize(760, 520);
        registro.setLocationRelativeTo(null);
        registro.setVisible(true);
        registro.setResizable(false);
    }//GEN-LAST:event_botonAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
