/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedor;

import AccesoDatos.ConexionBD;
import AccesoDatos.FachadaBD;
import controlador.controladorProveedor;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Proveedor;

/**
 *
 * @author Fernando
 */
public class PanelRegistroProveedor extends javax.swing.JPanel {

    public FachadaBD fachada;
    public ConexionBD conexion;
    Empleado permisosEmpleado;
    controladorProveedor controlProveedor;

    /**
     * Creates new form PanelRegistroClientes
     */
    public PanelRegistroProveedor(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlProveedor = new controladorProveedor(fachada);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrarProveedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoNit = new javax.swing.JTextField();
        campoDireccionP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombreP = new javax.swing.JTextField();
        campoTelefonoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Proveedor"));

        botonRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        botonRegistrarProveedor.setText("Registrar");
        botonRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarProveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Nit *");

        campoDireccionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionPActionPerformed(evt);
            }
        });

        jLabel4.setText("Dirección");

        jLabel2.setText("Nombre *");

        jLabel5.setText("Teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNit, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTelefonoP, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(campoNombreP)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegistrarProveedor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarProveedor)
                .addGap(211, 211, 211))
        );

        getAccessibleContext().setAccessibleName("Registrar Cliente");
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarProveedorActionPerformed
        // TODO add your handling code here:
        String nombre = campoNombreP.getText();
        String nit = campoNit.getText();
        String telefono = campoTelefonoP.getText();
        String direccion = campoDireccionP.getText();
        
        if (nombre.equals("") || nit.equals("")) {
            JOptionPane.showMessageDialog(null,"Llene todos los campos obligatorios");
        } else {
            Proveedor p = new Proveedor(nit, nombre, direccion, telefono, 0);
            boolean flag = controlProveedor.registrarProveedor(p);
            if (flag) {
                JOptionPane.showMessageDialog(null, "Se ha registrado satisfactoriamente el Proveedor");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al almacenar el proveedor");
            }
        }
    }//GEN-LAST:event_botonRegistrarProveedorActionPerformed

    private void campoDireccionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionPActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarProveedor;
    private javax.swing.JTextField campoDireccionP;
    private javax.swing.JTextField campoNit;
    private javax.swing.JTextField campoNombreP;
    private javax.swing.JTextField campoTelefonoP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    void limpiar() {
        campoNombreP.setText("");
        campoNit.setText("");
        campoTelefonoP.setText("");
        campoDireccionP.setText("");
    }
}
