/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Producto;

import AccesoDatos.FachadaBD;
import modelo.Empleado;

/**
 *
 * @author usuario
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelProducto
     */
    FachadaBD fachada;
    Empleado permisosEmpleado;
    public PanelProductos(FachadaBD f,Empleado pE) {
        permisosEmpleado = pE;
        fachada =f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        botonConsultar = new javax.swing.JButton();
        botonInsertar1 = new javax.swing.JButton();
        botonListarProductos = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(776, 351));

        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Producto"));
        panelOpciones.setPreferredSize(new java.awt.Dimension(123, 329));

        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos consultar.png"))); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.setToolTipText("Consultar Producto");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        botonInsertar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos insertar.png"))); // NOI18N
        botonInsertar1.setText("Nuevo");
        botonInsertar1.setToolTipText("Insertar Producto");
        botonInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertar1ActionPerformed(evt);
            }
        });

        botonListarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos listar.png"))); // NOI18N
        botonListarProductos.setText("Lista");
        botonListarProductos.setToolTipText("Listar Productos");
        botonListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(botonListarProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonInsertar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonInsertar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonListarProductos)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        panelCentral.setPreferredSize(new java.awt.Dimension(627, 329));

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelConsultarProducto obj = new PanelConsultarProducto(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertar1ActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelRegistroProducto obj = new PanelRegistroProducto(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);                          
       
    }//GEN-LAST:event_botonInsertar1ActionPerformed

    private void botonListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarProductosActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelListadoProductos obj = new PanelListadoProductos(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);                          
       
    }//GEN-LAST:event_botonListarProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonInsertar1;
    private javax.swing.JButton botonListarProductos;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
