/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Producto;

import AccesoDatos.FachadaBD;
import controlador.controladorProducto;
import controlador.controladorProveedor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Producto;
import modelo.Proveedor;
import vista.Proveedor.PanelListadoProveedores;

/**
 *
 * @author usuario
 */
public class PanelRegistroProducto extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistroProducto
     */
    controladorProducto controlador;
    controladorProveedor controladorProveedor;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    Proveedor proveedor;

    public PanelRegistroProducto(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlador = new controladorProducto(fachada);
        controladorProveedor = new controladorProveedor(fachada);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoPrecioC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoPrecioV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoProveedor = new javax.swing.JTextField();
        buscarProveedor = new javax.swing.JButton();
        botonRegistrarProducto = new javax.swing.JButton();
        opcionLista = new javax.swing.JRadioButton();
        campoNombreProveedor = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Producto"));
        setPreferredSize(new java.awt.Dimension(545, 279));

        jLabel2.setText("Id Producto *");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Precio Compra *");

        jLabel5.setText("Precio Venta *");

        jLabel6.setText("Proveedor *");

        buscarProveedor.setText("Buscar");
        buscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProveedorActionPerformed(evt);
            }
        });

        botonRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        botonRegistrarProducto.setText("Registrar");
        botonRegistrarProducto.setToolTipText("Insertar Producto");
        botonRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarProductoActionPerformed(evt);
            }
        });

        opcionLista.setText("Lista");

        campoNombreProveedor.setEditable(false);
        campoNombreProveedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombreProveedor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcionLista)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buscarProveedor))
                                    .addComponent(campoPrecioC))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDescripcion)
                            .addComponent(campoPrecioV)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegistrarProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProveedor)
                    .addComponent(opcionLista))
                .addGap(18, 18, 18)
                .addComponent(campoNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(botonRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarProductoActionPerformed
        // TODO add your handling code here:
        String idProducto = campoId.getText();
        String descripcion = campoDescripcion.getText();
        String precioCompra = campoPrecioC.getText();
        String precioVenta = campoPrecioV.getText();
        String idProveedor = campoProveedor.getText();

        if (idProducto.equals("") ||  precioCompra.equals("") || precioVenta.equals("") || idProveedor.equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios");
        } else {
            double pCompra = 0;
            double pVenta = 0;
            boolean valoresCorrectos = false;
            try {
                pCompra = Double.parseDouble(precioCompra);
                pVenta = Double.parseDouble(precioVenta);
                valoresCorrectos = true;
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(null, exp.getMessage() + ": " + "Ingrese un valor valido");
            }
            if (valoresCorrectos == false) {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el producto");
            } else {
                Producto p = new Producto();
                p.setidProducto(idProducto);
                p.setdescripcion(descripcion);
                p.setprecioCompra(pCompra);
                p.setprecioVenta(pVenta);
                p.setcantDisponible(0);
                p.setidProveedor(idProveedor);
                boolean registrado = controlador.registrarProducto(p);

                if (registrado == true) {
                    JOptionPane.showMessageDialog(null, "Producto registrado con exito");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar el producto");
                }
            }
        }
    }//GEN-LAST:event_botonRegistrarProductoActionPerformed
    
    public void setProveedor(Proveedor p){
        proveedor = p;
        campoProveedor.setText(p.getidProveedor());
        campoNombreProveedor.setText(p.getnombreProveedor());
    }
    
    void buscarLista(){
        PanelListadoProveedores listado = new PanelListadoProveedores(fachada, permisosEmpleado,4);
        listado.setPanelRegistroProducto(this);
        JFrame proveedores = new JFrame();
        proveedores.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(proveedores);
        proveedores.add(listado);
        proveedores.setSize(760, 520);
        proveedores.setLocationRelativeTo(null);
        proveedores.setVisible(true);
        proveedores.setResizable(false);
    }
    
    void buscarCodigo(){
        try{
            proveedor = controladorProveedor.consultarProveedor(campoProveedor.getText(),0).get(0);
            setProveedor(proveedor);
        }catch(Exception exp){
            JOptionPane.showMessageDialog(null,"No se encontro proveedor");
        }
    }
    
    private void buscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProveedorActionPerformed
        // TODO add your handling code here:
        if(opcionLista.isSelected()){
            buscarLista();
        }else{
            buscarCodigo();
        }
    }//GEN-LAST:event_buscarProveedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarProducto;
    private javax.swing.JButton buscarProveedor;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombreProveedor;
    private javax.swing.JTextField campoPrecioC;
    private javax.swing.JTextField campoPrecioV;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton opcionLista;
    // End of variables declaration//GEN-END:variables
}
