/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Producto;

import AccesoDatos.FachadaBD;
import controlador.controladorProducto;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.Producto;
import vista.Cliente.PanelRegistroCliente;
import vista.Compras.PanelRegistroCompra;
import vista.Ventas.PanelRegistroVenta;

/**
 *
 * @author usuario
 */
public class PanelListadoProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelListadoProductos
     */
    controladorProducto controlador;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    int opcion;
    PanelRegistroVenta ventasNuevas;
    PanelRegistroCompra comprasNuevas;
    JFrame frame;

    public PanelListadoProductos(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlador = new controladorProducto(fachada);
        initComponents();
        initSecundario();
        botonSeleccionar.setVisible(false);


    }
    
    /*
     * Constructor que se utiliza cuando se requiere un listado en una ventana aparte
     * @opcion se refiere a que clase esta instanciando
     * 1.PanelRegistroVenta
     * 2.PanelRegistroCompra
     * 3.
     */
    public PanelListadoProductos(FachadaBD f, Empleado pE, int op) {
        permisosEmpleado = pE;
        fachada = f;
        controlador = new controladorProducto(fachada);
        opcion = op;
        initComponents();
        initSecundario();
        botonSeleccionar.setEnabled(true);


    }

    private void initSecundario() {
        Object[][] datos = controlador.listarProductos();
        Object[] nCol = {"Id Producto", "Descripcion", "Precio Compra", "Precio Venta", "Cantidad Disponible", "Proveedor"};
        listaProductos.setModel(new DefaultTableModel(datos, nCol));
    }

    public void setPanelVentasNuevas(PanelRegistroVenta pVN) {
        ventasNuevas = pVN;
    }

    public void setComprasNuevas(PanelRegistroCompra comprasNuevas) {
        this.comprasNuevas = comprasNuevas;
    }
    
    public void setFrame(JFrame f){
        frame = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JTable();
        botonSeleccionar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Productos"));

        listaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProducto", "Descripcion", "Precio Compra", "Precio Venta", "Cantidad disponible", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listaProductos);

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSeleccionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionar)
                    .addComponent(botonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = listaProductos.getSelectedRow();

        if (fila != -1) {
            Producto p = new Producto();
            p = controlador.consultarProducto(listaProductos.getValueAt(fila, 0)+"",0).get(0);
            //p.setidProducto(listaProductos.getValueAt(fila, 0) + "");
            //p.setdescripcion(listaProductos.getValueAt(fila, 1) + "");
            //p.setprecioCompra(Double.parseDouble(listaProductos.getValueAt(fila, 2) + ""));
            //p.setprecioVenta(Double.parseDouble(listaProductos.getValueAt(fila, 3) + ""));
            //p.setcantDisponible(Integer.parseInt(listaProductos.getValueAt(fila, 4) + ""));
            //p.setidProveedor(listaProductos.getValueAt(fila, 5) + "");
            switch (opcion) {
                case 1:
                    ventasNuevas.setProducto(p);
                    break;
                case 2:
                    comprasNuevas.setProducto(p);
                    break;
            }
            frame.dispose();

        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        PanelRegistroProducto productoNuevo = new PanelRegistroProducto(fachada, permisosEmpleado);
        JFrame registro = new JFrame();
        registro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        registro.add(productoNuevo);
        registro.setSize(760, 520);
        registro.setLocationRelativeTo(null);
        registro.setVisible(true);
        registro.setResizable(false);
    }//GEN-LAST:event_botonAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaProductos;
    // End of variables declaration//GEN-END:variables
}
