/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Cliente;

import AccesoDatos.FachadaBD;
import controlador.controladorCliente;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Empleado;
import vista.Ventas.PanelRegistroVenta;
import vista.Ventas.PanelRegistroVentasAntiguas;
import vista.Ventas.PanelVentasXCliente;

/**
 *
 * @author usuario
 */
public class PanelListadoClientes extends javax.swing.JPanel {

    /**
     * Creates new form panelListadoClientes
     */
    controladorCliente controlCliente;
    DefaultTableModel modeloClientes;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    int opcion;
    PanelRegistroVentasAntiguas ventasAntiguas;
    PanelRegistroVenta ventasNuevas;
    PanelVentasXCliente ventasXcliente;
    JFrame frame;
    
    public PanelListadoClientes(FachadaBD f,Empleado pE) {
       
        initSecundario(f, pE);
         initComponents();
        botonSeleccionar.setVisible(false);
        
    }
    /*
     * Constructor que se utiliza cuando se requiere un listado en una ventana aparte
     * @opcion se refiere a que clase esta instanciando
     * 1.PanelRegistroVenta
     * 2.PanelRegistroVentasAntiguas
     * 3.PanelVentasXCliente
     */
    public PanelListadoClientes(FachadaBD f,Empleado pE,int op){
        
        initSecundario(f, pE);
        initComponents();
        opcion = op;
        botonSeleccionar.setEnabled(true);
    }
    
    private void initSecundario(FachadaBD f,Empleado pE){
        permisosEmpleado = pE;
        fachada=f;
        controlCliente = new controladorCliente(fachada);
        modeloClientes = new DefaultTableModel();
        modeloClientes.addColumn("Cedula");
        
        modeloClientes.addColumn("Nombre");
        modeloClientes.addColumn("Apellido");
        modeloClientes.addColumn("Direccion");
        modeloClientes.addColumn("Telefono");
        modeloClientes.addColumn("Saldo");
        
        Object[][] datos = controlCliente.listarClientes();
        for(int i=0;i<datos.length;i++){
            modeloClientes.addRow(datos[i]);
        }
    }
    
    public void setPanelVentasAntiguas(PanelRegistroVentasAntiguas pVA){
        ventasAntiguas = pVA;
    }
    
    public void setPanelVentasNuevas(PanelRegistroVenta pVN){
        ventasNuevas = pVN;
    }

    public void setVentasXcliente(PanelVentasXCliente vXC) {
        ventasXcliente = vXC;
    }
    
    public void setFrame(JFrame f){
        frame =f ;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        botonSeleccionar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Clientes"));

        tablaClientes.setModel(modeloClientes);
        jScrollPane1.setViewportView(tablaClientes);

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSeleccionar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionar)
                    .addComponent(botonAgregar))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = tablaClientes.getSelectedRow();
        
        if(fila !=-1){
            Cliente c = new Cliente();
            c.setidCliente(tablaClientes.getValueAt(fila,0)+"");
            c.setnombreCliente(tablaClientes.getValueAt(fila,1)+"");
            c.setapellidoCliente(tablaClientes.getValueAt(fila,2)+"");
            switch(opcion){
                case 1:
                    ventasNuevas.setCliente(c);
                    break;
                case 2:
                    ventasAntiguas.setCliente(c);
                    break;
                case 3:
                    ventasXcliente.setCliente(c);
                    break;
            }
            
            frame.dispose();

        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        PanelRegistroCliente clienteNuevo = new PanelRegistroCliente(fachada, permisosEmpleado);
        JFrame registro = new JFrame();
        registro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        registro.add(clienteNuevo);
        registro.setSize(760, 520);
        registro.setLocationRelativeTo(null);
        registro.setVisible(true);
        registro.setResizable(false);
    }//GEN-LAST:event_botonAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
