/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Compras;

import AccesoDatos.FachadaBD;
import controlador.controladorCompra;
import controlador.controladorItemCompra;
import controlador.controladorProducto;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Compra;
import modelo.Empleado;
import modelo.ItemCompra;
import modelo.Producto;
import modelo.Venta;
import vista.Ventas.PanelVentasXCliente;

/**
 *
 * @author usuario
 */
public class PanelConsultarCompra extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarCompra
     */
    controladorCompra controlCompra;
    controladorItemCompra controlItemCompra;
    controladorProducto controlProducto;
    DefaultTableModel modeloItems;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    Compra compra;

    public PanelConsultarCompra(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlProducto = new controladorProducto(fachada);
        controlItemCompra = new controladorItemCompra(fachada);
        controlCompra = new controladorCompra(fachada);
        modeloItems = new DefaultTableModel();
        modeloItems.addColumn("Producto");
        modeloItems.addColumn("Descripcion");
        modeloItems.addColumn("Cantidad");
        modeloItems.addColumn("Vlr Unitario");
        modeloItems.addColumn("Total");
        initComponents();
    }

    public void setCompra(Compra c) {
        compra = controlCompra.consultarCompra(c.getidCompra());
        llenarTabla();
    }

    private void llenarTabla() {
        campoEmpleado.setText(compra.getidEmpleado());
        campoFechaCompra.setText(compra.getfechaCompra());
        campoIdCompra.setText(compra.getidCompra());
        campoProveedor.setText(compra.getidProveedor());
        DecimalFormat formato = new DecimalFormat("###,###");
        campoTotalCompra.setText(formato.format(compra.getvlrTotal()));
        campoSaldoCompra.setText(formato.format(Double.parseDouble(compra.getsaldoCompra())));

        ArrayList<ItemCompra> datos = controlItemCompra.buscarItemCompra(compra.getidCompra());

        for (int i = 0; i < datos.size(); i++) {
            Producto p = new Producto();
            p = controlProducto.consultarProducto(datos.get(i).getidProducto(),0).get(0);

            String fila[] = new String[5];
            fila[0] = p.getidProducto();
            fila[1] = p.getdescripcion();
            fila[2] = "" + datos.get(i).getcantidad();
            fila[3] = formato.format(p.getprecioCompra());
            fila[4] = formato.format(datos.get(i).getvlrTotal());
            modeloItems.addRow(fila);
        }
    }

    private void consultarCompraCampo() {
        String idC = campoBuscar.getText();
        if (idC.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nro de compra");
        } else {
            compra = controlCompra.consultarCompra(idC);
            llenarTabla();
        }
    }

    private void consultarCompraLista() {
        PanelComprasXProveedor listado = new PanelComprasXProveedor(fachada, permisosEmpleado, 1);
        listado.setPanelConsulta(this);
        JFrame consulta = new JFrame();
        consulta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(consulta);
        consulta.add(listado);
        consulta.setSize(760, 520);
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        opcionLista = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoFechaCompra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoIdCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTotalCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoSaldoCompra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCompra = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        opcionLista.setText("Lista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(opcionLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(opcionLista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Compra"));

        jLabel1.setText("Fecha Compra");

        campoFechaCompra.setEditable(false);

        jLabel2.setText("Nro Compra");

        campoIdCompra.setEditable(false);

        jLabel3.setText("Proveedor");

        campoProveedor.setEditable(false);

        jLabel4.setText("Empleado");

        campoEmpleado.setEditable(false);

        jLabel5.setText("Total");

        campoTotalCompra.setEditable(false);

        jLabel6.setText("Saldo");

        campoSaldoCompra.setEditable(false);

        listaCompra.setModel(modeloItems);
        jScrollPane1.setViewportView(listaCompra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoFechaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(campoProveedor)
                            .addComponent(campoTotalCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoIdCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEmpleado)
                                    .addComponent(campoSaldoCompra)))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(campoSaldoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if (opcionLista.isSelected()) {
            consultarCompraLista();
        } else {
            consultarCompraCampo();
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoEmpleado;
    private javax.swing.JTextField campoFechaCompra;
    private javax.swing.JTextField campoIdCompra;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JTextField campoSaldoCompra;
    private javax.swing.JTextField campoTotalCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaCompra;
    private javax.swing.JRadioButton opcionLista;
    // End of variables declaration//GEN-END:variables
}
