/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Compras;

import AccesoDatos.FachadaBD;
import controlador.controladorCompra;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Compra;
import modelo.Empleado;
import modelo.Proveedor;
import modelo.Venta;
import vista.Proveedor.PanelListadoProveedores;

/**
 *
 * @author usuario
 */
public class PanelComprasXProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprasXProveedor
     */
    FachadaBD fachada;
    controladorCompra controlCompra;
    DefaultTableModel modeloCompras;
    Empleado permisosEmpleado;
    Proveedor proveedor;
    int opcion;
    PanelConsultarCompra panelConsulta;
    PanelRegistroPagoProveedor panelRegistroPagoProveedor;
    JFrame frame;

    public PanelComprasXProveedor(FachadaBD f, Empleado pE) {
        fachada = f;
        permisosEmpleado = pE;
        controlCompra = new controladorCompra(fachada);
        modeloCompras = new DefaultTableModel();
        modeloCompras.addColumn("Nro Compra");
        modeloCompras.addColumn("Empleado");
        modeloCompras.addColumn("Proveedor");
        modeloCompras.addColumn("Fecha");
        modeloCompras.addColumn("Total");
        modeloCompras.addColumn("Saldo");
        initComponents();
        botonSeleccionar.setVisible(false);
    }

    /*
     * 1. panelConsultaCompra
     * 2. panelRegistroPagoProveedor
     */
    public PanelComprasXProveedor(FachadaBD f, Empleado pE, int op) {
        fachada = f;
        permisosEmpleado = pE;
        opcion = op;
        controlCompra = new controladorCompra(fachada);
        modeloCompras = new DefaultTableModel();
        modeloCompras.addColumn("Nro Compra");
        modeloCompras.addColumn("Empleado");
        modeloCompras.addColumn("Proveedor");
        modeloCompras.addColumn("Fecha");
        modeloCompras.addColumn("Total");
        modeloCompras.addColumn("Saldo");
        initComponents();
        botonSeleccionar.setEnabled(true);
    }

    public void setPanelConsulta(PanelConsultarCompra panelConsulta) {
        this.panelConsulta = panelConsulta;
    }

    public void setPanelRegistroPagoProveedor(PanelRegistroPagoProveedor panelRegistroPagoProveedor) {
        this.panelRegistroPagoProveedor = panelRegistroPagoProveedor;
    }
    
    

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    public void setProveedor(Proveedor p) {
        int filas = modeloCompras.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloCompras.removeRow(i);
        }
        System.out.println("Va a asignar la lista de Compras");
        proveedor = p;
        ArrayList<Compra> listado = controlCompra.consultarComprasXProveedor(proveedor.getidProveedor());

        for (int i = 0; i < listado.size(); i++) {

            System.out.println("venta " + i);
            Object fila[] = new String[6];
            fila[0] = listado.get(i).getidCompra();
            fila[1] = listado.get(i).getidEmpleado();
            fila[2] = listado.get(i).getidProveedor();
            fila[3] = listado.get(i).getfechaCompra();
            fila[4] = listado.get(i).getvlrTotal() + "";
            fila[5] = listado.get(i).getsaldoCompra() + "";
            modeloCompras.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscar = new javax.swing.JButton();
        botonSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        botonAbono = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Compras Por Proveedor"));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        tablaCompras.setModel(modeloCompras);
        jScrollPane1.setViewportView(tablaCompras);

        botonAbono.setText("Abono");
        botonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAbono)
                        .addGap(18, 18, 18)
                        .addComponent(botonSeleccionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonSeleccionar)
                    .addComponent(botonAbono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        PanelListadoProveedores listado = new PanelListadoProveedores(fachada, permisosEmpleado, 3);
        listado.setPanelComprasXProveedor(this);
        JFrame proveedores = new JFrame();
        proveedores.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(proveedores);
        proveedores.add(listado);
        proveedores.setSize(760, 520);
        proveedores.setLocationRelativeTo(null);
        proveedores.setVisible(true);
        proveedores.setResizable(false);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = tablaCompras.getSelectedRow();

        if (fila != -1) {
            Compra c = new Compra();
            c.setidCompra(tablaCompras.getValueAt(fila, 0) + "");

            switch (opcion) {
                case 1:
                    panelConsulta.setCompra(c);
                    break;
                case 2:
                    panelRegistroPagoProveedor.setCompra(c);
                    break;
            }

            frame.dispose();

        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbonoActionPerformed
        // TODO add your handling code here:

        int fila = tablaCompras.getSelectedRow();

        if (fila != -1) {
            Compra c = new Compra();
            c.setidCompra(tablaCompras.getValueAt(fila, 0) + "");

            PanelRegistroPagoProveedor pago = new PanelRegistroPagoProveedor(fachada, permisosEmpleado);
            JFrame abono = new JFrame();
            abono.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            abono.add(pago);
            abono.setSize(760, 520);
            abono.setLocationRelativeTo(null);
            abono.setVisible(true);
            abono.setResizable(false);
            pago.buscarCompra(c.getidCompra());

        }
    }//GEN-LAST:event_botonAbonoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbono;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCompras;
    // End of variables declaration//GEN-END:variables
}
