/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Compras;

import AccesoDatos.FachadaBD;
import controlador.controladorCompra;
import controlador.controladorPagoProveedor;
import controlador.controladorProveedor;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Compra;
import modelo.Empleado;
import modelo.ItemCompra;
import modelo.PagoProveedor;
import modelo.Proveedor;
import vista.Proveedor.PanelListadoProveedores;

/**
 *
 * @author usuario
 */
public class PanelRegistroComprasAntiguas extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroComprasAntiguas
     */
    controladorCompra controlCompra;
    controladorPagoProveedor controlPagoProveedor;
    controladorProveedor controlProveedor;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    Proveedor proveedor;
    
    public PanelRegistroComprasAntiguas(FachadaBD f, Empleado pE) {
        fachada = f;
        permisosEmpleado = pE;
        controlCompra = new controladorCompra(fachada);
        controlPagoProveedor = new controladorPagoProveedor(fachada);
        controlProveedor = new controladorProveedor(fachada);
        initComponents();
    }

    public void setProveedor(Proveedor p) {
        this.proveedor = p;
        campoProveedor.setText(proveedor.getidProveedor()+" - "+proveedor.getnombreProveedor());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opcionPago = new javax.swing.JRadioButton();
        campoFecha = new com.toedter.calendar.JDateChooser();
        campoNroFactura = new javax.swing.JTextField();
        campoProveedor = new javax.swing.JTextField();
        campoValorFactura = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        botonBuscarProveedor = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Compras Antiguas"));

        jLabel1.setText("Fecha Compra");

        jLabel2.setText("Nro Factura");

        jLabel3.setText("Proveedor");

        jLabel4.setText("Valor Factura");

        opcionPago.setText("Pagó");

        campoProveedor.setEnabled(false);

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonBuscarProveedor.setText("Buscar");
        botonBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcionPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(campoNroFactura)
                            .addComponent(campoProveedor)
                            .addComponent(campoValorFactura))))
                .addGap(18, 18, 18)
                .addComponent(botonBuscarProveedor)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarProveedor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoValorFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionPago)
                    .addComponent(botonRegistrar))
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarProveedorActionPerformed
        // TODO add your handling code here:
        PanelListadoProveedores listado = new PanelListadoProveedores(fachada, permisosEmpleado, 2);
        listado.setPanelComprasAntiguas(this);
        JFrame proveedores = new JFrame();
        proveedores.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(proveedores);
        proveedores.add(listado);
        proveedores.setSize(760, 520);
        proveedores.setLocationRelativeTo(null);
        proveedores.setVisible(true);
        proveedores.setResizable(false);
    }//GEN-LAST:event_botonBuscarProveedorActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        boolean registrado;
        Date temp = campoFecha.getDate();
        String fecha  = temp.toString();
        String nroCompra = campoNroFactura.getText();
        String valorFactura = campoValorFactura.getText();
        String idProveedor = proveedor.getidProveedor();
        
        if (fecha.equals("") || nroCompra.equals("") || valorFactura.equals(evt)) {
            JOptionPane.showMessageDialog(null, "LLene todos los campos");
        } else {
            Compra c = new Compra();
            c.setidCompra(nroCompra);
            c.setfechaCompra(fecha);
            c.setidEmpleado(permisosEmpleado.getidEmpleado());
            c.setidProveedor(idProveedor);
            c.setvlrTotal(Double.parseDouble(valorFactura));
            c.setsaldoCompra(valorFactura);
            registrado = controlCompra.registrarCompra(c);

            if (registrado == true) {

                if (opcionPago.isSelected()) {
                    PagoProveedor pago = new PagoProveedor();
                    pago.setnroPago(1);
                    pago.setfechaPago(fecha);
                    pago.setidCompra(c.getidCompra());
                    pago.setidEmpleado(permisosEmpleado.getidEmpleado());
                    pago.setmonto(Double.parseDouble(valorFactura));
                    controlPagoProveedor.registrarPagoProveedor(pago);
                }

                JOptionPane.showMessageDialog(null, "La compra" + c.getidCompra()
                        + " se registro con exito");
            } else {
                JOptionPane.showMessageDialog(null, "La compra no se pudo registrar");
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarProveedor;
    private javax.swing.JButton botonRegistrar;
    private com.toedter.calendar.JDateChooser campoFecha;
    private javax.swing.JTextField campoNroFactura;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JTextField campoValorFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton opcionPago;
    // End of variables declaration//GEN-END:variables
}
