/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Compras;

import AccesoDatos.FachadaBD;
import modelo.Empleado;

/**
 *
 * @author Fernando
 */
public class PanelCompras extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    FachadaBD fachada;
    Empleado permisosEmpleado;
    public PanelCompras(FachadaBD f,Empleado pE) {
        permisosEmpleado = pE;
        fachada=f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bCrearCompra = new javax.swing.JButton();
        bConsultarCompra = new javax.swing.JButton();
        botonCompraAntigua = new javax.swing.JButton();
        botonComprasXProveedor = new javax.swing.JButton();
        botonPagoProveedores = new javax.swing.JButton();
        botonConsultaPagosProveedores = new javax.swing.JButton();
        panelCentralClientes = new javax.swing.JPanel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Compras"));

        bCrearCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra crear.png"))); // NOI18N
        bCrearCompra.setText("Nueva");
        bCrearCompra.setToolTipText("Nueva Compra");
        bCrearCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearCompraActionPerformed(evt);
            }
        });

        bConsultarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra consultar.png"))); // NOI18N
        bConsultarCompra.setText("Consultar");
        bConsultarCompra.setToolTipText("Nueva Venta");
        bConsultarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarCompraActionPerformed(evt);
            }
        });

        botonCompraAntigua.setText("Compra Antigua");
        botonCompraAntigua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompraAntiguaActionPerformed(evt);
            }
        });

        botonComprasXProveedor.setText("Compras Por Proveedor");
        botonComprasXProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprasXProveedorActionPerformed(evt);
            }
        });

        botonPagoProveedores.setText("Pago Proveedores");
        botonPagoProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagoProveedoresActionPerformed(evt);
            }
        });

        botonConsultaPagosProveedores.setText("Consulta Pagos");
        botonConsultaPagosProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaPagosProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonPagoProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonComprasXProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(bConsultarCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonConsultaPagosProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCompraAntigua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCrearCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCrearCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCompraAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonComprasXProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonPagoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConsultaPagosProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelCentralClientes.setPreferredSize(new java.awt.Dimension(630, 340));

        javax.swing.GroupLayout panelCentralClientesLayout = new javax.swing.GroupLayout(panelCentralClientes);
        panelCentralClientes.setLayout(panelCentralClientesLayout);
        panelCentralClientesLayout.setHorizontalGroup(
            panelCentralClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        panelCentralClientesLayout.setVerticalGroup(
            panelCentralClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentralClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentralClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Menú Clientes");
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearCompraActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelRegistroCompra obj=new PanelRegistroCompra(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);

    }//GEN-LAST:event_bCrearCompraActionPerformed

    private void bConsultarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarCompraActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelConsultarCompra obj=new PanelConsultarCompra(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bConsultarCompraActionPerformed

    private void botonCompraAntiguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompraAntiguaActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelRegistroComprasAntiguas obj=new PanelRegistroComprasAntiguas(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonCompraAntiguaActionPerformed

    private void botonComprasXProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprasXProveedorActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelComprasXProveedor obj=new PanelComprasXProveedor(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonComprasXProveedorActionPerformed

    private void botonConsultaPagosProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaPagosProveedoresActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelConsultarPagoProveedor obj=new PanelConsultarPagoProveedor(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonConsultaPagosProveedoresActionPerformed

    private void botonPagoProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagoProveedoresActionPerformed
        // TODO add your handling code here:
        panelCentralClientes.removeAll();
        PanelRegistroPagoProveedor obj=new PanelRegistroPagoProveedor(fachada,permisosEmpleado);
        panelCentralClientes.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonPagoProveedoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultarCompra;
    private javax.swing.JButton bCrearCompra;
    private javax.swing.JButton botonCompraAntigua;
    private javax.swing.JButton botonComprasXProveedor;
    private javax.swing.JButton botonConsultaPagosProveedores;
    private javax.swing.JButton botonPagoProveedores;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCentralClientes;
    // End of variables declaration//GEN-END:variables
}
