/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Compras;

import AccesoDatos.FachadaBD;
import controlador.controladorCompra;
import controlador.controladorPagoProveedor;
import controlador.controladorProveedor;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Compra;
import modelo.Empleado;
import modelo.PagoProveedor;
import modelo.Proveedor;

/**
 *
 * @author usuario
 */
public class PanelRegistroPagoProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoPagoProveedor
     */
    controladorCompra controlCompra;
    controladorProveedor controlProveedor;
    controladorPagoProveedor controlPagoProveedor;
    Compra compra;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    
    public PanelRegistroPagoProveedor(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlCompra = new controladorCompra(fachada);
        controlProveedor = new controladorProveedor(fachada);
        controlPagoProveedor = new controladorPagoProveedor(fachada);
        compra = new Compra();
       
        initComponents();
        campoFechaAbono.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdCompra = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoFechaCompra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoAbono = new javax.swing.JTextField();
        botonRealizarPago = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoFechaAbono = new com.toedter.calendar.JDateChooser();
        opcionLista = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos Proveedores"));

        jLabel1.setText("Nro Compra");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Proveedor");

        campoProveedor.setEditable(false);

        jLabel3.setText("Fecha Compra");

        campoFechaCompra.setEditable(false);

        jLabel4.setText("Saldo");

        campoSaldo.setEditable(false);

        jLabel5.setText("Abonar");

        botonRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago.png"))); // NOI18N
        botonRealizarPago.setText("Realizar Pago");
        botonRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarPagoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha");

        opcionLista.setText("Lista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(campoProveedor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(campoFechaCompra)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(campoAbono)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opcionLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(botonBuscar)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(campoFechaAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addComponent(botonRealizarPago, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(campoIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonBuscar)
                        .addComponent(jLabel6)
                        .addComponent(opcionLista))
                    .addComponent(campoFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void buscarCompra(String idCom) {
        campoIdCompra.setText(idCom);
        compra = controlCompra.consultarCompra(idCom);
        campoFechaCompra.setText(compra.getfechaCompra());
        campoSaldo.setText("" + compra.getsaldoCompra());
        
        Proveedor p = controlProveedor.consultarProveedor(compra.getidProveedor(), 0).get(0);
        campoProveedor.setText(p.getnombreProveedor());
    }
    
    void setCompra(Compra c) {
        buscarCompra(c.getidCompra());
    }
    
    void buscarLista(){
        PanelComprasXProveedor listado = new PanelComprasXProveedor(fachada, permisosEmpleado, 2);
        listado.setPanelRegistroPagoProveedor(this);
        JFrame consulta = new JFrame();
        consulta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(consulta);
        consulta.add(listado);
        consulta.setSize(760, 520);
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }
    
    void buscarCodigo(){
        String idCom = campoIdCompra.getText();
        if (idCom.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nro de Compra");
        } else {
            buscarCompra(idCom);
        }
    }
    
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if(opcionLista.isSelected()){
            buscarLista();
        }else{
            buscarCodigo();
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
    
    private void botonRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarPagoActionPerformed
        // TODO add your handling code here:
        if (compra.getidCompra() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nro de Compra");
        } else if (Double.parseDouble(compra.getsaldoCompra()) == 0) {
            JOptionPane.showMessageDialog(null, "No debe nada");
        } else if (campoAbono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el monto a abonar");
        } else {
            int abono = 0;
            try {
                abono = Integer.parseInt(campoAbono.getText());
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(null, exp.getMessage() + " :"
                        + "Ingrese un valor valido para el monto a abonar");
            }
            
            if (abono <= 0) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor mayor a cero"
                        + " para el monto a abonar");
            } else if (abono > Double.parseDouble(compra.getsaldoCompra())) {
                JOptionPane.showMessageDialog(null, "El monto a bonar debe ser"
                        + " menor o igual a el saldo");
            } else {
                int indice = controlPagoProveedor.getIndicePagoProveedor(compra.getidCompra());
                PagoProveedor pp = new PagoProveedor();
                pp.setnroPago(indice + 1);
                pp.setidCompra(compra.getidCompra());
                pp.setfechaPago(campoFechaAbono.getDate().toString());
                pp.setmonto(abono);
                pp.setidEmpleado(permisosEmpleado.getidEmpleado());
                boolean registrado = controlPagoProveedor.registrarPagoProveedor(pp);
                
                if(registrado){
                    JOptionPane.showMessageDialog(null, "Pago registrado con exito");
                    buscarCompra(compra.getidCompra());
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo registrar el pago");
                }
            }
        }
        
    }//GEN-LAST:event_botonRealizarPagoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRealizarPago;
    private javax.swing.JTextField campoAbono;
    private com.toedter.calendar.JDateChooser campoFechaAbono;
    private javax.swing.JTextField campoFechaCompra;
    private javax.swing.JTextField campoIdCompra;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton opcionLista;
    // End of variables declaration//GEN-END:variables

    
}
