/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import AccesoDatos.FachadaBD;
import modelo.Empleado;
import vista.Cliente.PanelClientes;
import vista.Compras.PanelCompras;
import vista.Empleado.PanelEmpleados;
import vista.Producto.PanelProductos;
import vista.Proveedor.PanelProveedores;
import vista.Ventas.PanelVentas;

/**
 *
 * @author Fernando
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    FachadaBD fachada;
    Empleado permisosEmpleado;
    public InterfazPrincipal(FachadaBD f,Empleado pE) {
        fachada=f;
        permisosEmpleado =pE;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bCliente = new javax.swing.JButton();
        bProducto = new javax.swing.JButton();
        bVentas = new javax.swing.JButton();
        bCompra = new javax.swing.JButton();
        bProveedor = new javax.swing.JButton();
        botonEmpleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Facturación Empresarial (SGFE)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones"));

        bCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        bCliente.setText("Clientes");
        bCliente.setToolTipText("");
        bCliente.setFocusable(false);
        bCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClienteActionPerformed(evt);
            }
        });

        bProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N
        bProducto.setText("Productos");
        bProducto.setToolTipText("Productos");
        bProducto.setFocusable(false);
        bProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoActionPerformed(evt);
            }
        });

        bVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta.png"))); // NOI18N
        bVentas.setText("Ventas");
        bVentas.setToolTipText("Venta");
        bVentas.setFocusable(false);
        bVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentasActionPerformed(evt);
            }
        });

        bCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra.png"))); // NOI18N
        bCompra.setText("Compras");
        bCompra.setToolTipText("Compras");
        bCompra.setFocusable(false);
        bCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompraActionPerformed(evt);
            }
        });

        bProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores (2).png"))); // NOI18N
        bProveedor.setText("Proveedor");
        bProveedor.setToolTipText("Proveedores");
        bProveedor.setFocusable(false);
        bProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedorActionPerformed(evt);
            }
        });

        botonEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        botonEmpleado.setText("Empleados");
        botonEmpleado.setToolTipText("Empleado");
        botonEmpleado.setFocusable(false);
        botonEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEmpleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nataly 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEmpleado)
                .addGap(18, 18, 18)
                .addComponent(bVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelPrincipal.setName(""); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClienteActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        PanelClientes obj=new PanelClientes(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bClienteActionPerformed

    private void bProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedorActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        PanelProveedores obj=new PanelProveedores(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bProveedorActionPerformed

    private void bProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoActionPerformed
        panelPrincipal.removeAll();
        PanelProductos obj = new PanelProductos(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
        
    }//GEN-LAST:event_bProductoActionPerformed

    private void bVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentasActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        PanelVentas obj = new PanelVentas(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
        
    }//GEN-LAST:event_bVentasActionPerformed

    private void botonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        PanelEmpleados obj=new PanelEmpleados(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonEmpleadoActionPerformed

    private void bCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompraActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        PanelCompras obj=new PanelCompras(fachada,permisosEmpleado);
        panelPrincipal.add(obj);
        obj.setSize(1000, 500);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_bCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCliente;
    private javax.swing.JButton bCompra;
    private javax.swing.JButton bProducto;
    private javax.swing.JButton bProveedor;
    private javax.swing.JButton bVentas;
    private javax.swing.JButton botonEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
