/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import AccesoDatos.*;
import controlador.controladorCliente;
import controlador.controladorItemVenta;
import controlador.controladorPagoCliente;
import controlador.controladorProducto;
import controlador.controladorVenta;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Empleado;
import modelo.ItemVenta;
import modelo.PagoCliente;
import modelo.Producto;
import modelo.Venta;
import vista.Cliente.PanelListadoClientes;
import vista.Producto.PanelListadoProductos;

/**
 *
 * @author usuario
 */
public class PanelRegistroVenta extends javax.swing.JPanel {

    /**
     * Creates new form panelNuevaVenta
     */
    Producto p;
    Cliente c;
    controladorProducto controlProducto;
    controladorCliente controlCliente;
    controladorVenta controlVenta;
    controladorItemVenta controlItemVenta;
    controladorPagoCliente controlPagoCliente;
    DefaultTableModel modeloProducto;
    double iva;
    double totalVenta;
    Calendar calendario;
    String dia;
    int mes;
    String anio;
    String fecha;
    int minuto;
    int hora;
    int seg;
    String numFact;
    FachadaBD fachada;
    Empleado permisosEmpleado;

    public PanelRegistroVenta(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlProducto = new controladorProducto(fachada);
        controlCliente = new controladorCliente(fachada);
        controlVenta = new controladorVenta(fachada);
        controlItemVenta = new controladorItemVenta(fachada);
        controlPagoCliente = new controladorPagoCliente(fachada);
        modeloProducto = new DefaultTableModel();
        p = new Producto();
        c = new Cliente();

        initComponents();
        totalVenta = 0;
        calendario = new GregorianCalendar();
        dia = String.valueOf(calendario.get(Calendar.DATE));
        mes = calendario.get(Calendar.MONTH) + 1;
        anio = String.valueOf(calendario.get(Calendar.YEAR));
        fecha = dia + "-" + mes + "-" + anio;
        minuto = calendario.get(Calendar.MINUTE);
        hora = calendario.get(Calendar.HOUR);
        seg = calendario.get(Calendar.SECOND);
        numFact = dia + mes + anio + minuto;

        jLabel6.setText(fecha);
        campoIdVenta.setText(numFact);
    }
    
    public void setCliente(Cliente cliente){
        c= cliente;
        campoIdCliente.setText(c.getidCliente());
        campoNombreCliente.setText(c.getnombreCliente());
        campoApellidoCliente.setText(c.getapellidoCliente());
    }
    
    public void setProducto(Producto producto){
        p = producto;
        campoIdProducto.setText(p.getidProducto());
        campoDescripcion.setText(p.getdescripcion());
        DecimalFormat formato = new DecimalFormat("###,###");
        campoPrecioV.setText(formato.format(p.getprecioVenta()));
        campoCantDisp.setText(p.getcantDisponible()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdCliente = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        etiquetaTotal = new javax.swing.JLabel();
        opcionPago = new javax.swing.JRadioButton();
        botonRegistrarVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoIdVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoNombreCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoApellidoCliente = new javax.swing.JTextField();
        botonBuscarProducto = new javax.swing.JButton();
        campoIdProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoPrecioV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoCantDisp = new javax.swing.JTextField();
        bAgregarItem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Venta"));

        jLabel1.setText("Cliente");

        botonBuscarCliente.setText("Buscar");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto");

        tablaProductos.setModel(modeloProducto);
        jScrollPane1.setViewportView(tablaProductos);
        modeloProducto.addColumn("Producto");
        modeloProducto.addColumn("Descripción");
        modeloProducto.addColumn("Cantidad");
        modeloProducto.addColumn("Valor Unitario");
        modeloProducto.addColumn("IVA");
        modeloProducto.addColumn("Valor Total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("TOTAL:");

        etiquetaTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiquetaTotal.setText("0");

        opcionPago.setText("Pagó");

        botonRegistrarVenta.setText("Hacer Venta");
        botonRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVentaActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setText("Número Factura:");

        campoIdVenta.setEditable(false);
        campoIdVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campoIdVenta.setForeground(new java.awt.Color(51, 51, 255));

        jLabel8.setText("Nombre");

        campoNombreCliente.setEditable(false);

        jLabel9.setText("Apellidos");

        campoApellidoCliente.setEditable(false);

        botonBuscarProducto.setText("Buscar ");
        botonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarProductoActionPerformed(evt);
            }
        });

        campoIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio Venta");

        campoPrecioV.setEditable(false);
        campoPrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioVActionPerformed(evt);
            }
        });

        jLabel10.setText("Cant Dispo");

        campoCantDisp.setEditable(false);

        bAgregarItem.setText("Agregar a Factura");
        bAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarItemActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad");

        jLabel12.setText("Descripcion");

        campoDescripcion.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonBuscarCliente))
                                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonBuscarProducto))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(bAgregarItem)))
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCantDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(opcionPago)
                                .addGap(18, 18, 18)
                                .addComponent(botonRegistrarVenta)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoCantDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarItem)
                    .addComponent(jLabel11)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTotal)
                    .addComponent(opcionPago)
                    .addComponent(botonRegistrarVenta)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        PanelListadoClientes listado = new PanelListadoClientes(fachada, permisosEmpleado,1);
        listado.setPanelVentasNuevas(this);
        JFrame clientes = new JFrame();
        clientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(clientes);
        clientes.add(listado);
        clientes.setSize(760, 520);
        clientes.setLocationRelativeTo(null);
        clientes.setVisible(true);
        clientes.setResizable(false);
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarProductoActionPerformed
        // TODO add your handling code here:
        PanelListadoProductos listado = new PanelListadoProductos(fachada, permisosEmpleado,1);
        listado.setPanelVentasNuevas(this);
        JFrame productos = new JFrame();
        productos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(productos);
        productos.add(listado);
        productos.setSize(760, 520);
        productos.setLocationRelativeTo(null);
        productos.setVisible(true);
        productos.setResizable(false);
    }//GEN-LAST:event_botonBuscarProductoActionPerformed

    private void bAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarItemActionPerformed
        // TODO add your handling code here:
        if (p.getidProducto() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        } else if(p.getcantDisponible()==0){
            JOptionPane.showMessageDialog(null, "El producto " +
                    p.getidProducto()+" no esta disponible");
        }else{
            iva = 0;
            int cantIngresada = 0;
            try {
                cantIngresada = Integer.parseInt(campoCantidad.getText());
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(null, exp.getMessage() + ": "
                        + "Ingrese un valor valido para cantidad");
            }

            if (cantIngresada <= 0) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad mayor que cero");
            } else if (cantIngresada > p.getcantDisponible()) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad menor o igual"
                        + " a la cantidad disponible");
            } else {
                boolean esta = false;
                for (int i = 0; i < modeloProducto.getRowCount(); i++) {
                    esta = p.getidProducto().equals(modeloProducto.getValueAt(i, 0));
                    if (esta == true) {
                        break;
                    }
                }

                if (esta == true) {
                    JOptionPane.showMessageDialog(null, "Ya agrego el producto "
                            + p.getidProducto());
                } else {
                    String item[] = new String[6];
                    item[0] = p.getidProducto();
                    item[1] = p.getdescripcion();
                    item[2] = "" + cantIngresada;
                    DecimalFormat formato = new DecimalFormat("###,###");
                    item[3] = formato.format(p.getprecioVenta());
                    item[4] = iva + "";
                    double total = cantIngresada * p.getprecioVenta() + cantIngresada * p.getprecioVenta() * (iva / 100);
                    item[5] = formato.format(total);
                    modeloProducto.addRow(item);
                    totalVenta += total;
                    etiquetaTotal.setText(formato.format(totalVenta));
                }
            }
        }

    }//GEN-LAST:event_bAgregarItemActionPerformed

    private void campoPrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioVActionPerformed

    private void botonRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVentaActionPerformed
        // TODO add your handling code here:
        if (c.getidCliente() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        } else if (totalVenta <= 0) {
            JOptionPane.showMessageDialog(null, "No ha agregado productos");
        } else {
            Venta v = new Venta();
            v.setidVenta(campoIdVenta.getText());
            v.setidEmpleado(permisosEmpleado.getidEmpleado());
            v.setidCliente(c.getidCliente());
            v.setfechaVenta(fecha);
            v.setvlrTotal(totalVenta);
            v.setsaldoVenta(totalVenta);
            boolean registrado = controlVenta.registrarVenta(v);
            
            if (registrado == true) {
                for (int i = 0; i < modeloProducto.getRowCount(); i++) {
                    ItemVenta item = new ItemVenta();
                    item.setnroItem("" + (i + 1));
                    item.setidVenta(numFact);
                    item.setidProducto("" + modeloProducto.getValueAt(i, 0));
                    item.setcantidad(Integer.parseInt("" + modeloProducto.getValueAt(i, 2)));
                    item.setiva(Double.parseDouble("" + modeloProducto.getValueAt(i, 4)));
                    item.setvlrTotal(Double.parseDouble("" + modeloProducto.getValueAt(i, 5)));
                    controlItemVenta.registrarItemVenta(item);
                }

                if (opcionPago.isSelected()) {
                    PagoCliente pago= new PagoCliente();
                    pago.setnroPago(1);
                    pago.setfechaPago(fecha);
                    pago.setidVenta(v.getidVenta());
                    pago.setidEmpleado(permisosEmpleado.getidEmpleado());
                    pago.setmonto(totalVenta);
                    controlPagoCliente.registrarPagoCliente(pago);
                }
                
                JOptionPane.showMessageDialog(null, "La Venta"+
                        v.getidVenta()+" se registro con exito");

            } else {
                JOptionPane.showMessageDialog(null, "No se puedo realizar la venta");
            }
        }

    }//GEN-LAST:event_botonRegistrarVentaActionPerformed

    private void campoIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarItem;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonBuscarProducto;
    private javax.swing.JButton botonRegistrarVenta;
    private javax.swing.JTextField campoApellidoCliente;
    private javax.swing.JTextField campoCantDisp;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoIdCliente;
    private javax.swing.JTextField campoIdProducto;
    private javax.swing.JTextField campoIdVenta;
    private javax.swing.JTextField campoNombreCliente;
    private javax.swing.JTextField campoPrecioV;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcionPago;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
