/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import AccesoDatos.FachadaBD;
import controlador.controladorCliente;
import controlador.controladorPagoCliente;
import controlador.controladorVenta;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Empleado;
import modelo.PagoCliente;
import modelo.Venta;
import vista.Cliente.PanelListadoClientes;

/**
 *
 * @author usuario
 */
public class PanelRegistroVentasAntiguas extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroVentasAntiguas
     */
    controladorCliente controlCliente;
    controladorVenta controlVenta;
    controladorPagoCliente controlPagoCliente;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    Cliente cliente;

    public PanelRegistroVentasAntiguas(FachadaBD f, Empleado pE) {
        fachada = f;
        permisosEmpleado = pE;
        controlCliente = new controladorCliente(fachada);
        controlVenta = new controladorVenta(fachada);
        controlPagoCliente = new controladorPagoCliente(fachada);
        initComponents();
    }

    public void setCliente(Cliente c) {
        cliente = c;
        campoCliente.setText(cliente.getidCliente() + " - " + cliente.getnombreCliente() + " " + cliente.getapellidoCliente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNroFactura = new javax.swing.JTextField();
        campoCliente = new javax.swing.JTextField();
        campoValor = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoFecha = new com.toedter.calendar.JDateChooser();
        opcionPagoR = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Ventas Antiguas"));

        jLabel1.setText("Nro Factura");

        jLabel2.setText("Cliente");

        jLabel3.setText("Valor Factura");

        campoCliente.setEditable(false);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha Venta");

        opcionPagoR.setText("Pagó");
        opcionPagoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPagoRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(campoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(campoCliente))
                                .addGap(18, 18, 18)
                                .addComponent(botonBuscar))
                            .addComponent(opcionPagoR))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(campoNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(opcionPagoR)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrar)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        PanelListadoClientes listado = new PanelListadoClientes(fachada, permisosEmpleado, 2);
        listado.setPanelVentasAntiguas(this);
        JFrame clientes = new JFrame();
        clientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(clientes);
        clientes.add(listado);
        clientes.setSize(760, 520);
        clientes.setLocationRelativeTo(null);
        clientes.setVisible(true);
        clientes.setResizable(false);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            String fecha = campoFecha.getDate().toString();
            String idCliente = cliente.getidCliente();
            String nroFactura = campoNroFactura.getText();
            String valorFactura = campoValor.getText();
           

            if (fecha.equals("") || idCliente.equals("") || nroFactura.equals("") || valorFactura.equals("")) {
                JOptionPane.showMessageDialog(null, "LLene todos los campos");
            } else {

                Venta v = new Venta();
                v.setidVenta(nroFactura);
                v.setidEmpleado(permisosEmpleado.getidEmpleado());
                v.setidCliente(idCliente);
                v.setfechaVenta(fecha);
                v.setvlrTotal(Integer.parseInt(valorFactura));
                v.setsaldoVenta(Integer.parseInt(valorFactura));
                boolean registrado = controlVenta.registrarVenta(v);
                if (registrado == true) {
                    if (opcionPagoR.isSelected()==true) {
                        PagoCliente pago = new PagoCliente();
                        pago.setnroPago(1);
                        pago.setfechaPago(fecha);
                        pago.setidVenta(v.getidVenta());
                        pago.setidEmpleado(permisosEmpleado.getidEmpleado());
                        pago.setmonto(Integer.parseInt(valorFactura));
                        controlPagoCliente.registrarPagoCliente(pago);
                    }
                    JOptionPane.showMessageDialog(null, "La Venta"
                            + v.getidVenta() + " se registro con exito");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar la venta");
                }
            }
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(null,"Error: "+ exp.getMessage());
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void opcionPagoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPagoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionPagoRActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoCliente;
    private com.toedter.calendar.JDateChooser campoFecha;
    private javax.swing.JTextField campoNroFactura;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton opcionPagoR;
    // End of variables declaration//GEN-END:variables
}
