/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import AccesoDatos.FachadaBD;
import controlador.controladorItemVenta;
import controlador.controladorProducto;
import controlador.controladorVenta;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.ItemVenta;
import modelo.Producto;
import modelo.Venta;

/**
 *
 * @author usuario
 */
public class PanelConsultarVenta extends javax.swing.JPanel {

    /**
     * Creates new form panelConsultarVenta
     */
    controladorVenta controlVenta;
    controladorItemVenta controlItemVenta;
    controladorProducto controlProducto;
    DefaultTableModel modeloItem;
    FachadaBD fachada;
    Empleado permisosEmpleado;
    Venta venta;

    public PanelConsultarVenta(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlVenta = new controladorVenta(fachada);
        controlItemVenta = new controladorItemVenta(fachada);
        controlProducto = new controladorProducto(fachada);

        modeloItem = new DefaultTableModel();
        modeloItem.addColumn("Producto");
        modeloItem.addColumn("Descripción");
        modeloItem.addColumn("Cantidad");
        modeloItem.addColumn("Valor Unitario");
        modeloItem.addColumn("IVA");
        modeloItem.addColumn("Valor Total");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        campoBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        opcionLista = new javax.swing.JRadioButton();
        panelVistaVenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaItems = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        campoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoIdVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();

        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        opcionLista.setText("Lista");

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBuscar)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(opcionLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(botonBuscar)))
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(opcionLista))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        panelVistaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Venta"));

        jLabel1.setText("Fecha Venta");

        campoFecha.setEnabled(false);

        tablaItems.setModel(modeloItem);
        jScrollPane1.setViewportView(tablaItems);

        jLabel2.setText("Cliente");

        campoCliente.setEnabled(false);
        campoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Empleado");

        campoEmpleado.setEnabled(false);

        jLabel4.setText("Nro Venta");

        campoIdVenta.setEnabled(false);

        jLabel5.setText("Total");

        campoTotal.setEnabled(false);

        jLabel6.setText("Saldo");

        campoSaldo.setEnabled(false);

        javax.swing.GroupLayout panelVistaVentaLayout = new javax.swing.GroupLayout(panelVistaVenta);
        panelVistaVenta.setLayout(panelVistaVentaLayout);
        panelVistaVentaLayout.setHorizontalGroup(
            panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(panelVistaVentaLayout.createSequentialGroup()
                        .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(campoFecha)
                            .addComponent(campoTotal))
                        .addGap(18, 18, 18)
                        .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoSaldo)
                            .addComponent(campoIdVenta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEmpleado, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        panelVistaVentaLayout.setVerticalGroup(
            panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVistaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelVistaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVistaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setVenta(Venta v) {
        venta = controlVenta.consultarVenta(v.getidVenta());
        llenarTabla();
    }
    
    private void consultarVentaCampo() {
        String idVenta = campoBuscar.getText();

        if (idVenta.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nro de Venta");
        } else {
            venta = controlVenta.consultarVenta(idVenta);
            llenarTabla();
        }
    }

    private void llenarTabla() {
        campoIdVenta.setText(venta.getidVenta());
        campoCliente.setText(venta.getidCliente());
        campoEmpleado.setText(venta.getidEmpleado());
        campoFecha.setText(venta.getfechaVenta());
        DecimalFormat formato = new DecimalFormat("###,###");
        campoTotal.setText(formato.format(venta.getvlrTotal()));
        campoSaldo.setText(formato.format(venta.getsaldoVenta()));

        ArrayList<ItemVenta> datos = controlItemVenta.buscarItemVenta(venta.getidVenta());

        for (int i = 0; i < datos.size(); i++) {
            Producto p = controlProducto.consultarProducto(datos.get(i).getidProducto(),0).get(0);

            String fila[] = new String[6];
            fila[0] = datos.get(i).getidProducto();
            fila[1] = p.getdescripcion();
            fila[2] = "" + datos.get(i).getcantidad();
            fila[3] = formato.format(p.getprecioVenta());
            fila[4] = "" + datos.get(i).getiva();
            fila[5] = formato.format(datos.get(i).getvlrTotal());
            modeloItem.addRow(fila);
        }
    }

    private void consultarVentaLista() {
        PanelVentasXCliente listado = new PanelVentasXCliente(fachada, permisosEmpleado, 1);
        listado.setPanelConsulta(this);
        JFrame consulta = new JFrame();
        consulta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(consulta);
        consulta.add(listado);
        consulta.setSize(760, 520);
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }

    private void campoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoClienteActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if (opcionLista.isSelected()) {
            consultarVentaLista();
        } else {
            consultarVentaCampo();
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoEmpleado;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoIdVenta;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcionLista;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelVistaVenta;
    private javax.swing.JTable tablaItems;
    // End of variables declaration//GEN-END:variables
}
