/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import AccesoDatos.FachadaBD;
import controlador.controladorCliente;
import controlador.controladorPagoCliente;
import controlador.controladorVenta;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Empleado;
import modelo.PagoCliente;
import modelo.Venta;

/**
 *
 * @author usuario
 */
public class PanelRegistroPagoCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoPagoCliente
     */
    controladorPagoCliente controlPagoCliente;
    controladorVenta controlVenta;
    controladorCliente controlCliente;
    Venta venta;
   
    FachadaBD fachada;
    Empleado permisosEmpleado;
    
    public PanelRegistroPagoCliente(FachadaBD f, Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        controlPagoCliente = new controladorPagoCliente(fachada);
        controlVenta = new controladorVenta(fachada);
        controlCliente = new controladorCliente(fachada);
        venta = new Venta();
        
        initComponents();
        campoFechaPago.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarVentaa = new javax.swing.JButton();
        campoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoFechaVenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoAbono = new javax.swing.JTextField();
        botonRealizarPago = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoFechaPago = new com.toedter.calendar.JDateChooser();
        opcionLista = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos Clientes"));

        jLabel1.setText("Nro Venta");

        jLabel2.setText("Cliente");

        botonBuscarVentaa.setText("Buscar");
        botonBuscarVentaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVentaaActionPerformed(evt);
            }
        });

        campoCliente.setEditable(false);

        jLabel3.setText("Fecha  Venta");

        campoFechaVenta.setEditable(false);

        jLabel4.setText("Saldo");

        campoSaldo.setEditable(false);
        campoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSaldoActionPerformed(evt);
            }
        });

        jLabel5.setText("Abonar");

        botonRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago.png"))); // NOI18N
        botonRealizarPago.setText("Realizar Pago");
        botonRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarPagoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha");

        opcionLista.setText("Lista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opcionLista)
                                .addGap(10, 10, 10)
                                .addComponent(botonBuscarVentaa)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campoFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                            .addComponent(campoCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoFechaVenta)
                                    .addComponent(campoAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRealizarPago)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonBuscarVentaa)
                        .addComponent(jLabel6)
                        .addComponent(opcionLista))
                    .addComponent(campoFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void buscarVenta(String idVenta) {
        campoIdVenta.setText(idVenta);
        venta = controlVenta.consultarVenta(idVenta);
        Cliente c = controlCliente.consultarCliente(venta.getidCliente(), 0).get(0);
        campoCliente.setText(c.getnombreCliente() + " " + c.getapellidoCliente());
        campoFechaVenta.setText(venta.getfechaVenta());
        DecimalFormat formato = new DecimalFormat("###,###");
        campoSaldo.setText(formato.format(venta.getsaldoVenta()));
    }
    
    void setVenta(Venta v) {
        buscarVenta(v.getidVenta());
    }
    
    void buscarLista(){
        PanelVentasXCliente listado = new PanelVentasXCliente(fachada, permisosEmpleado, 2);
        listado.setPanelRegistroPagoCliente(this);
        JFrame consulta = new JFrame();
        consulta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        listado.setFrame(consulta);
        consulta.add(listado);
        consulta.setSize(760, 520);
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }
    
    void buscarCodigo(){
        String idVenta = campoIdVenta.getText();
        if (idVenta.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el numero de Venta");
        } else {
            buscarVenta(idVenta);
        }
    }
    
    private void botonBuscarVentaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVentaaActionPerformed
        // TODO add your handling code here:
        if(opcionLista.isSelected()){
            buscarLista();
        }else{
            buscarCodigo();
        }
    }//GEN-LAST:event_botonBuscarVentaaActionPerformed
    
    private void botonRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarPagoActionPerformed
        // TODO add your handling code here:

        if (venta.getidVenta() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nro de venta");
        } else if (venta.getsaldoVenta() <= 0) {
            JOptionPane.showMessageDialog(null, "No debe nada");
        } else if (campoAbono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el monto a abonar");
        } else {
            int abono = 0;
            try {
                abono = Integer.parseInt(campoAbono.getText());
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(null, exp.getMessage() + " :"
                        + "Ingrese un valor valido para el monto a abonar");
            }
            
            if (abono <= 0) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor mayor a cero"
                        + " para el monto a abonar");
            } else if (abono > venta.getsaldoVenta()) {
                JOptionPane.showMessageDialog(null, "El monto a bonar debe ser"
                        + " menor o igual a el saldo");
            } else {
                int indice = controlPagoCliente.getIndicePagoCliente(venta.getidVenta());
                System.out.println("indice de pago "+venta.getidVenta()+":" +indice);
                PagoCliente pc = new PagoCliente();
                pc.setnroPago(indice + 1);
                pc.setidVenta(venta.getidVenta());
                pc.setfechaPago(campoFechaPago.getDate().toString());
                pc.setmonto(abono);
                pc.setidEmpleado(permisosEmpleado.getidEmpleado());
                boolean registrado =controlPagoCliente.registrarPagoCliente(pc);
                if(registrado){
                    JOptionPane.showMessageDialog(null, "Pago registrado con exito");
                    buscarVenta(venta.getidVenta());
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo registrar el pago");
                }
                
            }
        }
    }//GEN-LAST:event_botonRealizarPagoActionPerformed

    private void campoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSaldoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarVentaa;
    private javax.swing.JButton botonRealizarPago;
    private javax.swing.JTextField campoAbono;
    private javax.swing.JTextField campoCliente;
    private com.toedter.calendar.JDateChooser campoFechaPago;
    private javax.swing.JTextField campoFechaVenta;
    private javax.swing.JTextField campoIdVenta;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton opcionLista;
    // End of variables declaration//GEN-END:variables

}
