/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import AccesoDatos.FachadaBD;
import modelo.Empleado;

/**
 *
 * @author usuario
 */
public class PanelVentas extends javax.swing.JPanel {

    /**
     * Creates new form panelVenta
     */
    FachadaBD fachada;
    Empleado permisosEmpleado;
    public PanelVentas(FachadaBD f,Empleado pE) {
        permisosEmpleado = pE;
        fachada = f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        botonNuevaVenta = new javax.swing.JButton();
        botonConsultarVenta = new javax.swing.JButton();
        botonAntiguas = new javax.swing.JButton();
        botonVentasXCliente = new javax.swing.JButton();
        botonPagoCliente = new javax.swing.JButton();
        botonConsultaPagoCliente = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion Ventas"));

        botonNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CrearVenta.png"))); // NOI18N
        botonNuevaVenta.setText("Nueva Venta");
        botonNuevaVenta.setToolTipText("Nueva Venta");
        botonNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaVentaActionPerformed(evt);
            }
        });

        botonConsultarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarVenta.png"))); // NOI18N
        botonConsultarVenta.setText("Consultar");
        botonConsultarVenta.setToolTipText("Consultar Venta");
        botonConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarVentaActionPerformed(evt);
            }
        });

        botonAntiguas.setText("Ventas Antiguas");
        botonAntiguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAntiguasActionPerformed(evt);
            }
        });

        botonVentasXCliente.setText("Ventas Por Cliente");
        botonVentasXCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasXClienteActionPerformed(evt);
            }
        });

        botonPagoCliente.setText("Pago Clientes");
        botonPagoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagoClienteActionPerformed(evt);
            }
        });

        botonConsultaPagoCliente.setText("Consulta Pagos");
        botonConsultaPagoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaPagoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAntiguas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVentasXCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPagoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultaPagoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConsultarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAntiguas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVentasXCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonPagoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConsultaPagoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaVentaActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelRegistroVenta obj = new PanelRegistroVenta(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonNuevaVentaActionPerformed

    private void botonConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarVentaActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelConsultarVenta obj = new PanelConsultarVenta(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonConsultarVentaActionPerformed

    private void botonAntiguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAntiguasActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelRegistroVentasAntiguas obj = new PanelRegistroVentasAntiguas(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonAntiguasActionPerformed

    private void botonVentasXClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasXClienteActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelVentasXCliente obj = new PanelVentasXCliente(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonVentasXClienteActionPerformed

    private void botonPagoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagoClienteActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelRegistroPagoCliente obj = new PanelRegistroPagoCliente(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonPagoClienteActionPerformed

    private void botonConsultaPagoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaPagoClienteActionPerformed
        // TODO add your handling code here:
        panelCentral.removeAll();
        PanelConsultarPagoCliente obj = new PanelConsultarPagoCliente(fachada,permisosEmpleado);
        panelCentral.add(obj);
        obj.setSize(794, 478);
        obj.validate();
        obj.setVisible(true);
    }//GEN-LAST:event_botonConsultaPagoClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAntiguas;
    private javax.swing.JButton botonConsultaPagoCliente;
    private javax.swing.JButton botonConsultarVenta;
    private javax.swing.JButton botonNuevaVenta;
    private javax.swing.JButton botonPagoCliente;
    private javax.swing.JButton botonVentasXCliente;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
